### ISSUE TITLE
move ays templates relevant to this automation to this repo

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/ays_gig_github_dev_process#3]
ays template dir will be result

make sure that installer of cockpit uses also this ays_templates dir

**Comment by zaibon** [comment]
Why do we want to move templates here ? What the benefits.
Github servies are going to be used for support as well, not only Github integration. So this will lead to duplication or not really good organization.

**Comment by despiegk** [comment]
OK agree

**Comment by FastGeert** [comment]
It also does not make sense to just throw everything at one large pile.

the support tools also make use of github, so I think it makes sense to combine the dev & support github ays templates in this repo.

We need to rename it though to follow the convention.
