### ISSUE TITLE
Storycard progress calculation

### ISSUE THREAD

**Issue by bart-at-mobicage** [Jumpscale/ays_gig_github_dev_process#30]
It would be handy if the time left in a storycard is added under the list with checkboxes. Maybe a progress bar could be added as well to visualize the process.

**Comment by FastGeert** [comment]
Summarize all estimations of open and inprogress. Use http://progressed.io/bar/25 to create the progressbars.

**Comment by bart-at-mobicage** [comment]
It would be useful as well to see these statistics for every assignee as well.
