### ISSUE TITLE
install script for cockpit with github_automation tools inside

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/ays_gig_github_dev_process#6]
- input params
  - ip addr (ssh key is loaded in mem)
  - github url for cockpit_... repo (ssh key required to get this repo is in mem) 
- start from a ubuntu 14.04 and 16.04 with know private key
- use cuisine to get cockpit in docker (should be existing method)
- checkout this repo on right location in the cockpit, make sure all is appropriately installed

**Comment by FastGeert** [comment]
@despiegk The guys are confused what the goal is of this FR.
I checked it with both @muhamadazmy & @zaibon 

Can you please explain what you want to achieve?

**Comment by zaibon** [comment]
I'm not sure what exactly mean
> use cuisine to get cockpit in docker (should be existing method)

We don't have method to deploy a complete cockpit from cuisine. 
In cuisine we have a method to install the [jscockpit](github.com/Jumpscale/jscockpit/) server but not all the component around it.

**Comment by ashraffouda** [comment]
this is still not clear to me

**Comment by FastGeert** [comment]
@despiegk Where should this script be installed?

**Comment by rkhamis** [comment]
This is no longer relevant, I think
